### ISSUE TITLE
What coordinate frame is used for the output network.xml?

### ISSUE THREAD

**Issue by AHolliday** [matsim-org/josm-matsim-plugin#110]
I just used this plugin to create a network.xml for the city of Laval, Quebec.  Everything seemed to work fine, I can load the network.xml into OTFVis and it looks right.  But inside the xml file, I see that the nodes have coordinates like:

> x="-8215734.765365568" y="5713339.197381425"

This isn't lat,lon clearly.  All the x and y values are similar (approximately x=-8,21xxxx, y=571xxxx) so I'm guessing this is some kind of meter-like global cooridnate system.  But what coordinate system is it?  Normally this would be specified in the config.xml, but this plugin doesn't seem to produce such a file.  Or maybe it does, but I'm missing how to produce that output?

**Comment by nkuehnel** [comment]
You need to set the projection of the coordinate system from within JOSM in the standard JOSM preferences.

**Comment by AHolliday** [comment]
Thanks!
