### ISSUE TITLE
Exporting .osm into shapefile

### ISSUE THREAD

**Issue by Hotlineblinn** [matsim-org/josm-matsim-plugin#114]
Hello, there.

Quick question regarding josm matsim plugin,
When exporting osm into .shp file,  is it normal to get 2 separate shp files for both link and node (As attached)?

Thank you in advance.

![image](https://user-images.githubusercontent.com/76731360/110200540-dac35180-7ea1-11eb-959a-6089b3027cf5.png)

**Comment by nkuehnel** [comment]
Yes, this function basically mimics  the behavior of 
https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/utils/gis/matsim2esri/network/Nodes2ESRIShape.java

and 

https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/utils/gis/matsim2esri/network/Links2ESRIShape.java
