### ISSUE TITLE
DataIntegrityProblemException

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#25]
Adding a way or node to the layer and undoing it again leads to a "DataIntegrityProblemException: Primitive must be part of the dataset:" when trying to access the referrers of the primitive.

**Comment by michaz** [comment]
Puh. Der Fehler tauch noch an anderen Stellen auf. Haben wir eine Idee, warum das so ist oder seit wann das so ist? Hat das was mit JOSM-Updates zu tun? Ich sehe da nicht auf Anhieb was, was bei uns geändert wurde. Wir visiten doch seit Ewigkeiten auch removete Sachen, oder?
