### ISSUE TITLE
link ref persists after relation deletion

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#27]
1 load pt scenario
2 delete stop relations
3 write out transit schedule

-> link refs still appear in the schedule

**Comment by michaz** [comment]
Let's write a (failing) test for that.

**Comment by nkuehnel** [comment]
upon deletion, a relationMembersChanged(..) event is thrown first, whereafter the primitivesRemoved(..) event arises. so the information about previously hold relation members is already lost in the moment we realize the deletion. might want to handle it on relationMemberChanged(...) ...

**Comment by nkuehnel** [comment]
since facilities are now always created by platforms and their osm-id, there is no trace to which facility a stop-relation belonged to after all its members are deleted. the id tag of the stop relation is now useless as it does not define the facility.
