### ISSUE TITLE
Use GeoTools JOSM plugin instead of embedding class files

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#32]
Hi,
When several plugins use the same library we ask to plugin authors to not embed those libraries in the plugin jar, but to depend on an external plugin.
That's particularly the case for Geotools, which is used by a lot of plugins.
I am not familiar with Gradle so I won't be able to make a PR, but can you please see how to do that ?
The idea is to fetch the geotools.jar from OSM SVN during compilation and to add the directive Plugin-Requires: geotools in Manifest.

See examples there: 
https://github.com/kendzi/TombPlugin/pull/16
https://github.com/GeoKnow/OSMRec/issues/3

Thanks,
Vincent

**Comment by don-vip** [comment]
I have setup a Maven repository containing JOSM core and plugins, so you can use it in your Gradle file to get JOSM Geotools plugin: 

https://josm.openstreetmap.de/nexus/content/repositories/public
https://josm.openstreetmap.de/nexus/content/repositories/public/org/openstreetmap/josm/plugins/geotools/SNAPSHOT/maven-metadata.xml

It should be quite easy now :)

**Comment by nkuehnel** [comment]
Thanks! We currently believe that we don't even need geotools though

**Comment by michaz** [comment]
It's a transitive dependency of MATSim, but not of the part we are using. We are now excluding Geotools explicitly.

**Comment by don-vip** [comment]
this is even better! thanks :)

**Comment by michaz** [comment]
And thanks for the Maven server. :-)

**Comment by michaz** [comment]
Iiik, can't do that: Gradle doesn't like the version-less SNAPSHOT designation:

https://travis-ci.org/matsim-org/josm-matsim-plugin/builds/87896420
