### ISSUE TITLE
Bad version v0.5.2

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#33]
From https://josm.openstreetmap.de/plugin there are two major problems with release 0.5.2:

matsim.jar;https://github.com/matsim-org/josm-matsim-plugin/releases/download/v0.5.2/matsim.jar
	Manifest-Version: 1.0
	Plugin-Date: 2015-11-06 14:23
	**Plugin-Version: v0.5.1**
	Plugin-Mainversion: 8882
	**Created-By: 1.8.0_25 (Oracle Corporation)**

The version in manifest is incorrect => the plugin won't be updated for end users
The plugin has been built with JDK8. All plugins must run with JDK7, can you please rebuild it with correct version and latest JDK7?

**Comment by nkuehnel** [comment]
Thanks, updated the jar
