### ISSUE TITLE
Remove log4j classes from jar

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#34]
the plugin currently contains the classes of Apache Log4j.

It conflicts with the log4j JOSM plugin.

It seems the library is not actually used, so the best option might be to simply drop it in the gradle build file.

**Comment by nkuehnel** [comment]
I'm afraid the library is indeed used for the matsim core functionalities and is therefore required upon build

**Comment by floscher** [comment]
This should now no longer be a problem. The plugin classpaths are now separated since https://josm.openstreetmap.de/changeset/12322/josm .

**Comment by don-vip** [comment]
You're right. There are probably more important issues to deal with :)
