### ISSUE TITLE
Update to JOSM 10599

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#45]
We have finally switched to Java 8.
One breaking change: org.openstreetmap.josm.gui.mappaint.styleelement.LabelCompositionStrategy has become a functional interface, the plugin needs adaptation:

java.lang.IncompatibleClassChangeError: class org.matsim.contrib.josm.MapRenderer$Properties has interface org.openstreetmap.josm.gui.mappaint.styleelement.LabelCompositionStrategy as super class

**Comment by michaz** [comment]
Yay!
