### ISSUE TITLE
Ways with Euclidic length 0.0 and a tagged length get length not-a-number

### ISSUE THREAD

**Issue by michaz** [matsim-org/josm-matsim-plugin#46]
<img width="693" alt="screen shot 2016-07-23 at 12 56 56" src="https://cloud.githubusercontent.com/assets/520916/17077582/03f78fa8-50d5-11e6-83fe-ee908a5a45e5.png">

**Comment by floscher** [comment]
This issue is caused by the following line, when `way.getLength()` evaluates to 0:
https://github.com/matsim-org/josm-matsim-plugin/blob/d8e0407862c53057f0aea3f991355c0da2e1907b/src/main/java/org/matsim/contrib/josm/model/NetworkModel.java#L339-L341
