### ISSUE TITLE
Plugin must be updated to JOSM 12881+

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#65]
See https://josm.openstreetmap.de/ticket/15310#comment:6

**Comment by floscher** [comment]
I prepared PR #64, which fixes this amongst other things.
Pull request #66 contains only the changes from #64, which fix API compatibility, nothing else.

**Comment by nkuehnel** [comment]
hey , thanks much. will do #66 first and look into #64 soon!

**Comment by nkuehnel** [comment]
Nevermind, will merge #64 right away with the updated unit tests. Thanks again!

**Comment by floscher** [comment]
Great :tada:, if you have comments or questions about the changes, feel free to ask me. A bit of documentation about the gradle-josm-plugin and how to setup and use it can be found here:
* https://github.com/floscher/gradle-josm-plugin/blob/master/docs/Setup.md (that's already done in #64)
* https://github.com/floscher/gradle-josm-plugin/blob/master/docs/Tasks.md (what the new tasks introduced by the plugin do)

**Comment by nkuehnel** [comment]
will, do! :)
