### ISSUE TITLE
New links and nodes are not saved in xml output 

### ISSUE THREAD

**Issue by moritzhohenfellner** [matsim-org/josm-matsim-plugin#69]
When creating new links/nodes in an existing MATSim layer (and applying the link template) these are displayed in JOSM but are not saved into the XML file.

**Comment by nkuehnel** [comment]
Thanks, will look into that

**Comment by sebhoerl** [comment]
Any progress / ideas on that, @nkuehnel ? @moritzhohenfellner would need this for his thesis work

**Comment by floscher** [comment]
I just tried to reproduce it with version 8e0407862c53057f0aea3f991355c0da2e1907b (v0.8.5) , but for me new nodes and links appear in the XML file.

My steps (in case I did it differently than you):
* download some OSM data through the normal download dialog
* from the menu select `MATSim › Convert to MATSim layer`
* draw new nodes and links
* select the edges and open menu `Presets › MATSim › Link`. Set the values to something unusual (so you'll recognize the special links later)
* `Ctrl+S`

When I then open the resulting XML file, the nodes and links are present.
Is that what didn't work for you?

**Comment by nkuehnel** [comment]
@sebhoerl thanks for reminding me, unfortunately I did not have time to look at this lately. It does appear working for me as well though. Could you check again if this problem persists on your side?

**Comment by sebhoerl** [comment]
@moritzhohenfellner , can you update your example file + the steps to reproduce, please?

**Comment by moritzhohenfellner** [comment]
Thank you for taking care of this.

**Comment by moritzhohenfellner** [comment]
Thank you for taking care of this issue.

I just updated my JOSM version and the plugins. Please find below all the version information I get from JOSM. Unfortunatly I can still reproduce the problem:

- Open JOSM
- MATSim: Import MATSim Scenario (File: https://polybox.ethz.ch/index.php/s/basEmcjaBlBt5vA)
(Mercator projection)
- Draw new Links
- Presets: MATSim: Link
- CMD+S
>> No warnings 
>> The last modified date of the file is updated but the new links are not in the XML



-------------------- From JOSM Help: Status ---------------------------------------
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2017-12-31 03:09:43 +0100 (Sun, 31 Dec 2017)
Build-Date:2017-12-31 02:33:46
Revision:13265
Relative:URL: ^/trunk

Identification: JOSM/1.5 (13265 de) Mac OS X 10.11.6
OS Build number: Mac OS X 10.11.6 (15G1611)
Memory Usage: 815 MB / 1820 MB (452 MB allocated, but free)
Java version: 1.8.0_151-b12, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 69731520 1680x1050
Maximum Screen Size: 1680x1050
Dataset consistency test: No problems found

Plugins:
+ apache-commons (33668)
+ apache-http (32699)
+ jts (32699)
+ matsim (v0.7.8-15-gf75deaf-dirty)

**Comment by nkuehnel** [comment]
There's a new release (v0.8.7) please see if it works, it does for me. If you still get the issue could you tell what options in the matsim plugins preferences are set?

**Comment by moritzhohenfellner** [comment]
I just did the update but the problem unfortunately persists. 
I uploaded some screenshots of the settings and the object inspector of the new link and nodes.
Is it normal that the new links/nodes don't get an ID?

https://polybox.ethz.ch/index.php/s/ETabpVaj53OJRFV

**Comment by nkuehnel** [comment]
A possible reason could be that you just tried Single unconnected links like in the Screenshot. Since Clean Network is activated in your settings it will run the matsim Network Cleaner before writing to File,  which will remove unconnected links. So turning Clean network off could solve the issue? 
Also, do you have the link toggle dialog activated?

**Comment by moritzhohenfellner** [comment]
Turning the clean network option off did the trick. Thank you and sorry for the inconvenience!

**Comment by nkuehnel** [comment]
Glad it works :)
