### ISSUE TITLE
Id management broken

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#7]
When assigning an id by tag, all segments of a way get the same id.

![image](https://cloud.githubusercontent.com/assets/9531582/6167646/cc203686-b2bd-11e4-8a4d-52668964f19a.png)

**Comment by nkuehnel** [comment]
Also, after explicitely converting to matsim layer, the ids are no longer taken from the original id field but instead are copied from the actual id (which is the id in the internal column in the picture above).
This emerges from the combining of convert and import task. While the import task expected the valid ids in the "official" id field of links, the convert task had to rearrange the ids since the ids to be used were stored in the original id field.

![image](https://cloud.githubusercontent.com/assets/9531582/6167733/a2fcb184-b2be-11e4-9727-11ed07d8286a.png)

**Comment by nkuehnel** [comment]
As another result, delegating ids to links in a MATSim layer leads to validation errors due to the fact that multiple links share the same id, thus the layer cannot be saved.

**Comment by michaz** [comment]
Actually, part 1 is not so bad. It would have been an incomplete solution anyway (who says that the "_x"-pattern is what the user wants?). So for now, let's say the user has to split links if (s)he wants to assign custom ids.
