### ISSUE TITLE
Shifted Coordinates For Transit Schedule

### ISSUE THREAD

**Issue by kowinter** [matsim-org/josm-matsim-plugin#76]
When exporting a Transit Schedule from Josm with the MATSim-plugin, it uses a different coordinate transformation than for exporting the according network. Also I have found that networks downloaded before the update use a different transformation than the ones downloaded recently. 

As can be seen in the screenshot from VIA, the new network is more to the north than the "TransitSchedule" (and older networks generated before the update).

Can I change something in my settings to fix this, or this a bug?

![coordinatesshifted](https://user-images.githubusercontent.com/23402187/33934554-863d2612-dff9-11e7-97e2-f0a9a1c30c1c.PNG)

Thanks in advance!
K

**Comment by kowinter** [comment]
Putting everything on UTM transformation resolved the issue, thanks!

**Comment by nkuehnel** [comment]
Glad to hear that
