### ISSUE TITLE
errrors in transmission of MATSim data from OsmDataLayers to MATSim Layers

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#8]
Currently links created in an OsmDataLayer do no longer appear after an excplicit conversion to MATSim layer
![image](https://cloud.githubusercontent.com/assets/9531582/6171023/c29cdb94-b2d8-11e4-908b-dcf898fd136c.png) 
![image](https://cloud.githubusercontent.com/assets/9531582/6171035/ccd3ba9c-b2d8-11e4-9017-c3c4ae682c87.png)

**Comment by michaz** [comment]
Seems to work now.
