### ISSUE TITLE
Can't select schedule file

### ISSUE THREAD

**Issue by davibicudo** [matsim-org/josm-matsim-plugin#80]
Hi,
I tried a few different methods (eg loading the network before in xml, xml.gz...), but the browse schedule button is always greyed out. 
Both JOSM and plugin are up-to-date. 
Thanks for the support!
![2018-03-16 09_58_11-java openstreetmap editor](https://user-images.githubusercontent.com/28100741/37511979-0967c5f6-2901-11e8-8e2a-76db2558757e.png)

**Comment by nkuehnel** [comment]
Hi,
in the preferences there should be a tab for the plugin preferences. You will need to activate transit support in the Converter options.
Hope that helps

![image](https://user-images.githubusercontent.com/9531582/37519457-742b327a-2919-11e8-84a4-e679ec2ddc5c.png)

**Comment by davibicudo** [comment]
Hi, 
Works like a breeze :) 
Thanks a lot!

**Comment by nkuehnel** [comment]
Great!
