### ISSUE TITLE
Test setup broken

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#84]
The setup of the project seems broken, as tests are no longer run and dont compile on my machine.
@floscher is that related to the new gradle setup?

**Comment by floscher** [comment]
@nkuehnel I can't reproduce with the current master branch and the Travis build also seems to succeed. Have you made changes since then?

First thing I thought of was that another JOSM plugin on which this plugin depends changed incompatibly, but that doesn't seem to be the case.

**Comment by nkuehnel** [comment]
Ah nevermind, my Intellij setup was corrupted and imported a new gradle module for every source folder. thanks anyway, it works : )
