### ISSUE TITLE
Loss of data when switching layers and exception

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#9]
If multiple layers are opened, switching to one which should contain MATSim data does not show this in the toggle dialog. 

![image](https://cloud.githubusercontent.com/assets/9531582/6171163/7e1a29b2-b2d9-11e4-86bd-c5d6016ce94f.png)

Selecting a Way then results in exception

![image](https://cloud.githubusercontent.com/assets/9531582/6171200/c4141f5e-b2d9-11e4-8c88-9843b2822c56.png)

**Comment by michaz** [comment]
Seems to be fixed.
